### ISSUE TITLE
"matching" syntax no longer seems to work in Licenser 0.4

### ISSUE THREAD

**Issue by unascribed** [Minecrell/licenser#9]
Given the following:

```gradle
license {
	header = project.file('LICENSE')
	include '**/*.java'
	include '**/*.xml'
	
	matching(includes: ['**/org/greenrobot/essentials/**']) {
		header = project.file('greenrobot-LICENSE')
	}
	matching(includes:  ['**/com/firebase/geofire/**']) {
		header = project.file('geofire-LICENSE')
	}
}
```

I get the following error:

```
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: net.minecrell.gradle.licenser.LicenseProperties(net.minecrell.gradle.licenser.LicenseExtension_Decorated, org.gradle.api.tasks.util.PatternSet)
        at net.minecrell.gradle.licenser.LicenseExtension.matching(LicenseExtension.groovy:170)
        at net.minecrell.gradle.licenser.LicenseExtension$matching.callCurrent(Unknown Source)
        at net.minecrell.gradle.licenser.LicenseExtension.matching(LicenseExtension.groovy:150)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:464)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
        at build_10umfrx0ifpiwd4hofcdllfj0$_run_closure4.doCall(/home/una/Workspaces/Boba/argon/build.gradle:41)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
        at org.gradle.api.internal.plugins.DefaultConvention.configureExtension(DefaultConvention.java:348)
        at org.gradle.api.internal.plugins.DefaultConvention.access$500(DefaultConvention.java:46)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:303)
        at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:107)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:116)
        at build_10umfrx0ifpiwd4hofcdllfj0.run(/home/una/Workspaces/Boba/argon/build.gradle:36)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 62 more
```

**Comment by Minecrell** [comment]
Fixed in `0.4.1`, sorry about that :)
